# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
            #memory:
                #users:
                    #admin:
                        #password: $2y$12$/s3Sc8B/3Xc4kVApLVhXe.FRsrjQoR23BiyxN8RcqCMX91lYru99G
                        #roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        #Symfony\Component\Security\Core\User\User:
            #algorithm: bcrypt
            #cost: 12
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login:
                #login_path: login
                #check_path: login
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    #access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/products/list, roles: ROLE_ADMIN }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/, role: ROLE_ADMIN }